### ISSUE TITLE
Everything using Anvil GUI is broken

### ISSUE THREAD

**Issue by Ethmangameon** [Shiirroo/ManHunt#12]
I'm getting this error in console on 1.20.1 using the plugin everything in the plugin works fine other than this.

[14:28:10 INFO]: Ethmangameon issued server command: /manhunt config huntStartTime
[14:28:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'manhunt' in plugin ManHunt v1.7.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-145]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2347) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-145]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-145]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.shiirroo.manhunt.anvilgui.AnvilGUI
        at de.shiirroo.manhunt.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[manHunt-1.7.8.jar:?]
        at de.shiirroo.manhunt.command.subcommands.ConfigManHunt.AnvilGUI(ConfigManHunt.java:223) ~[manHunt-1.7.8.jar:?]
        at de.shiirroo.manhunt.command.subcommands.ConfigManHunt.AnvilGUISetup(ConfigManHunt.java:172) ~[manHunt-1.7.8.jar:?]
        at de.shiirroo.manhunt.command.subcommands.ConfigManHunt.perform(ConfigManHunt.java:70) ~[manHunt-1.7.8.jar:?]
        at de.shiirroo.manhunt.command.ManHuntCommandManager.onCommand(ManHuntCommandManager.java:94) ~[manHunt-1.7.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by Shiirroo** [comment]
Manhunt is currently not compatible with 1.20.1. Im working on a fix today.

**Comment by Shiirroo** [comment]
Its now Fixed

**Comment by Ethmangameon** [comment]
Thanks me and my friends are enjoying the update rn.

**Comment by Shiirroo** [comment]
> Thanks me and my friends are enjoying the update rn.

Glad to hear if you run into problems or want a new feature please let me know.

**Comment by Ethmangameon** [comment]
I have one issue I have but I don't think you could easily fix it I was trying to use MoistMC and use forge mods and it didn't work at all with the gui and didn't work with resetting the world
I contacted them on discord but I did not get a response

**Comment by Shiirroo** [comment]
ok, i'll take a look

**Comment by Shiirroo** [comment]
> I have one issue I have but I don't think you could easily fix it I was trying to use MoistMC and use forge mods and it didn't work at all with the gui and didn't work with resetting the world I contacted them on discord but I did not get a response

![image](https://github.com/Shiirroo/ManHunt/assets/44450151/c9733a7b-80d3-4f60-b100-faac9d5d61a2)

I couldn't find any problems resetting the world via the GUI.
